ASP.NETMVC/ASP.NETMVC/Controllers/LivresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ASP.NETMVC.Models;

namespace ASP.NETMVC.Controllers
{
    public class LivresController : Controller
    {
        private BiblioEntities db = new BiblioEntities();

        // GET: Livres
        public ActionResult Index(string sortOrder ,string  genre, string annee,string auteur)
        {
            //viewbag pour le trie
            ViewBag.AuteurTrie = String.IsNullOrEmpty(sortOrder) ? "Adesc" : "";
            ViewBag.AnneeTrie = sortOrder == "Date" ? "Date_desc" : "Date";

            

            //liste genre
            var GenreLst = new List<string>();

            var GenreQry = from g in db.LIVRES
                         orderby g.GENRES.LIBELLE_GENRE
                         select g.GENRES.LIBELLE_GENRE;

            GenreLst.AddRange(GenreQry.Distinct());
            ViewBag.genre = new SelectList(GenreLst);

            //liste auteur
            var auteurLst = new List<string>();
            var auteurQry = from a in db.LIVRES
                            orderby a.AUTEURS.NOM_AUTEUR
                            select a.AUTEURS.NOM_AUTEUR;
            auteurLst.AddRange(auteurQry.Distinct());
            ViewBag.auteur = new SelectList(auteurLst);

            //liste courant 
            
            //liste livre
            var livres = from l in db.LIVRES
                        select l;
            //filtrage annee
            if (!string.IsNullOrEmpty(annee))
            { 
                livres = livres.Where(s => s.ANNEE_EDITION.Value.Year == int.Parse(annee));
            }
            //filtrage genre
            if (!string.IsNullOrEmpty(genre))
            {
                livres = livres.Where(x => x.GENRES.LIBELLE_GENRE == genre);
            }
            //filtrage auteur
            if (!string.IsNullOrEmpty(auteur))
            {    
                livres = livres.Where(x => x.AUTEURS.NOM_AUTEUR == auteur);
            }
            //condition pour trie le livre
            switch (sortOrder)
            {
                case "Adesc":
                    livres = livres.OrderByDescending(s => s.AUTEURS.NOM_AUTEUR);
                    break;
                case "Date":
                    livres = livres.OrderBy(s => s.ANNEE_EDITION);
                    break;
                case "Date_desc":
                    livres = livres.OrderByDescending(s => s.ANNEE_EDITION);
                    break;
                default:
                    livres = livres.OrderBy(s => s.AUTEURS.NOM_AUTEUR);
                    break;
            }

            return View(livres);
        }

        // GET: Livres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LIVRES lIVRES = db.LIVRES.Find(id);
            if (lIVRES == null)
            {
                return HttpNotFound();
            }
            return View(lIVRES);
        }

        // GET: Livres/Create
        public ActionResult Create()
        {
            ViewBag.ID_AUTEUR = new SelectList(db.AUTEURS, "ID_AUTEUR", "NOM_AUTEUR");
            ViewBag.ID_GENRE = new SelectList(db.GENRES, "ID_GENRE", "LIBELLE_GENRE");
            return View();
        }

        // POST: Livres/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_LIVRE,ISBN,TITRE,EDITEUR,ANNEE_EDITION,ID_AUTEUR,ID_GENRE")] LIVRES lIVRES,HttpPostedFileBase LIVRE)
        {
            
            if (ModelState.IsValid)
            {

                var fileName = Path.GetFileName(LIVRE.FileName);
                var path = Path.Combine(Server.MapPath("~/pdf"), fileName);
                LIVRE.SaveAs(path);
                lIVRES.LIVRE = fileName;
                lIVRES.URL_LIVRE = "/pdf";
                //string path = Server.MapPath("~/pdf");
                //    try
                //    {
                //        if (Request.Files.Count > 0)
                //        {
                //            var fichier = Request.Files[0];
                //            if (fichier != null && fichier.ContentLength > 0)
                //            {
                //                var fileName = Path.GetFileName(fichier.FileName);
                //                var path = Path.Combine(Server.MapPath("~/pdf"), fileName);
                //                fichier.SaveAs(path);
                //                lIVRES.LIVRE = fileName;
                //                lIVRES.URL_LIVRE = "/pdf";
                //            }
                //        }
                //        ViewBag.Message = "File Uploaded Successfully!!";
                //    }
                //    catch
                //    {
                //        ViewBag.Message = "File upload failed!!";
                //        return View();
                //    }
                db.LIVRES.Add(lIVRES);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ID_AUTEUR = new SelectList(db.AUTEURS, "ID_AUTEUR", "NOM_AUTEUR", lIVRES.ID_AUTEUR);
            ViewBag.ID_GENRE = new SelectList(db.GENRES, "ID_GENRE", "LIBELLE_GENRE", lIVRES.ID_GENRE);
            return View(lIVRES);
        }

        // GET: Livres/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LIVRES lIVRES = db.LIVRES.Find(id);
            if (lIVRES == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_AUTEUR = new SelectList(db.AUTEURS, "ID_AUTEUR", "NOM_AUTEUR", lIVRES.ID_AUTEUR);
            ViewBag.ID_GENRE = new SelectList(db.GENRES, "ID_GENRE", "LIBELLE_GENRE", lIVRES.ID_GENRE);
            return View(lIVRES);
        }

        // POST: Livres/Edit/5
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_LIVRE,ISBN,TITRE,EDITEUR,ANNEE_EDITION,ID_AUTEUR,ID_GENRE")] LIVRES lIVRES)
        {
            if (ModelState.IsValid)
            {
                db.Entry(lIVRES).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ID_AUTEUR = new SelectList(db.AUTEURS, "ID_AUTEUR", "NOM_AUTEUR", lIVRES.ID_AUTEUR);
            ViewBag.ID_GENRE = new SelectList(db.GENRES, "ID_GENRE", "LIBELLE_GENRE", lIVRES.ID_GENRE);
            return View(lIVRES);
        }

        // GET: Livres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LIVRES lIVRES = db.LIVRES.Find(id);
            if (lIVRES == null)
            {
                return HttpNotFound();
            }
            return View(lIVRES);
        }

        // POST: Livres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LIVRES lIVRES = db.LIVRES.Find(id);
            db.LIVRES.Remove(lIVRES);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ASP.NETMVC/ASP.NETMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ibiblio</title>
    <link href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.min.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/5.0.2/flatly/bootstrap.css" rel="stylesheet" type="text/css" />

    <!--
        <link href="-https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

        link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css" />
        <script src="~/Scripts/modernizr-2.6.2.js"></script>
    -->

</head>
<body class="bg-dark">
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">@Html.ActionLink("IBiblio", "Index", "Livres", new { area = "" }, new { @class = "navbar-brand" })</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="~/Livres/Index">Livre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/Auteurs/Index">Auteur</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/Genres/Index">Genre</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="~/Courants/Index">Courant</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid bg-dark">
        @RenderBody()

        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    <!--
        <script src="~/Scripts/jquery-1.10.2.min.js"></script>
        <script src="~/Scripts/bootstrap.min.js"></script>
        <script src="-https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    -->
    <script src="https://code.jquery.com/jquery-3.5.1.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.min.js" type="text/javascript"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>